/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.53
 * Generated at: 2014-06-26 19:54:02 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import cn.huateng.dao.impl.PhoneInfoDAOImpl;
import cn.huateng.bean.Phone;
import java.util.ArrayList;
import cn.huateng.bean.Company;
import cn.huateng.dao.impl.CompanyDAOImpl;

public final class phoneupdate_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=GB18030");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=GB18030\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link href=\"../css/maincss.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");

	String  employeeid = (String)session.getAttribute("employeeid");
	if(employeeid==null){
		response.sendRedirect("index.jsp");
	}
	Phone phone=(Phone)request.getAttribute("phone");
	
		int line = 0;
		String s_line = request.getParameter("line");
		if(s_line!=null)
			line = Integer.parseInt(s_line);
		
		String error = request.getParameter("error");
		if(error!=null&&"update_phone_error".equals(error)){

      out.write("\r\n");
      out.write("\t\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\t\talert(\"修改图书失败，请重试!\");\r\n");
      out.write("\t\t\t</script>\r\n");

		}

      out.write("<div align=\"center\">\r\n");
      out.write("\t\t\t\t\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "top.jsp", out, false);
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("<div align=\"center\">\r\n");
      out.write("\t\t<table width=\"750\" border=\"0\" cellspacing=\"1\" cellpadding=\"1\">\r\n");
      out.write("\t\t\t \r\n");

	if (phone!=null)
	{

      out.write("\r\n");
      out.write("\t\t\t<tr> \r\n");
      out.write("\t\t\t\t<td><div align=\"center\">\r\n");
      out.write("\t\t\t\t\t<form action=\"/phonemarket/UpdatePhoneServlet\" method=\"post\">\r\n");
      out.write("\t\t\t    \t\t<table width=\"50%\" border=\"0\" cellpadding=\"1\" cellspacing=\"1\" class=\"td\">\r\n");

	if(line==0){

      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<tr> \r\n");
      out.write("\t\t\t\t\t\t\t\t<td width=\"30%\">手机流水号</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><div align=\"left\"> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
      out.print(phone.getPhoneid() );
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t</div></td>\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr> \r\n");
      out.write("\t\t\t\t\t\t\t\t<td>型号</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><div align=\"left\"> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
      out.print(phone.getPhonename() );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</div></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr> \r\n");
      out.write("\t\t\t\t\t\t\t\t<td>平台</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><div align=\"left\"> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
      out.print(phone.getPlatform() );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</div></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr> \r\n");
      out.write("\t\t\t\t\t\t\t\t<td>公司id</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><div align=\"left\">       \r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");

	int companyid= phone.getCompanyid();
CompanyDAOImpl companyrDAOImpl  = new CompanyDAOImpl();
Company company = companyrDAOImpl.cQueryById(companyid);

      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t");
      out.print(company.getName());
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t</div></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr> \r\n");
      out.write("\t\t\t\t\t\t\t\t<td>重量</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><div align=\"left\"> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
      out.print(phone.getWeight() );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</div></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr> \r\n");
      out.write("\t\t\t\t\t\t\t\t<td>屏幕</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><div align=\"left\"> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
      out.print(phone.getDisplay() );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</div></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr> \r\n");
      out.write("\t\t\t\t\t\t\t\t<td>售价</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><div align=\"left\"> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input name=\"price\" type=\"text\" size=\"25\" value=\"");
      out.print(phone.getPrice() );
      out.write("\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<font color=\"red\">*</font>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<tr> \r\n");
      out.write("\t\t\t\t\t\t\t\t<td>新品,精品标志</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><div align=\"left\"> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input name=\"type\" type=\"text\" size=\"25\" value=\"");
      out.print(phone.getType() );
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</div></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr> \r\n");
      out.write("\t\t\t\t\t\t\t\t<td>库存数量</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><div align=\"left\"> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input name=\"quantity\" type=\"text\" size=\"25\" value=\"");
      out.print(phone.getQuantity());
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</div></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<tr> \r\n");
      out.write("\t\t\t\t\t\t\t\t<td>相机</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><div align=\"left\"> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
      out.print(phone.getCamera() );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</div></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr> \r\n");
      out.write("\t\t\t\t\t\t\t\t<td>图片文件名</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><div align=\"left\"> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
      out.print(phone.getPicture() );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</div></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr> \r\n");
      out.write("\t\t\t\t\t\t\t\t<td>内存</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><div align=\"left\"> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
      out.print(phone.getRam() );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</div></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr> \r\n");
      out.write("\t\t\t\t\t\t\t\t<td colspan=\"2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div align=\"center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"phoneid\" value=\"");
      out.print(phone.getPhoneid());
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\t        <input type=\"submit\" value=\"更新 \">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\t\r\n");

	}else{

      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<tr> \r\n");
      out.write("\t\t\t\t\t\t\t    <td colspan=\"2\">&nbsp;&nbsp;修改手机成功!</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");

	}

      out.write("\t\t\r\n");

	}else{

      out.write("\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td><div align=\"center\">需要修改的信息不存在</div>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");

	}

      out.write("\t\r\n");
      out.write("\t\t\t         \t</table>\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t</div></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t \r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</div> \r\n");
      out.write("<div >\r\n");
      out.write("\t\t\t\t\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../user/bottom.jsp", out, false);
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
