/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.53
 * Generated at: 2014-06-26 19:53:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class top_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Cellphone Store</title>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("body{\r\n");
      out.write("\tmargin : 0px;\r\n");
      out.write("\tpadding : 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* ====== Navigation Main ====== */\r\n");
      out.write("div.navigation{\r\n");
      out.write("\tfont-family:\"微软雅黑 Light\", cursive;\r\n");
      out.write("\tbackground-color:#009;\r\n");
      out.write("\tpadding-top : 30px;\r\n");
      out.write("\tpadding-bottom : 30px;\r\n");
      out.write("\theight:170px;\r\n");
      out.write("\tfont-weight: bolder;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* ====== Navigation Menu ====== */\r\n");
      out.write("div.navigation>ul{\r\n");
      out.write("\tmargin : 0px;\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("div.navigation>ul>li{\r\n");
      out.write("\tlist-style : none;\r\n");
      out.write("\tdisplay : inline-block;\r\n");
      out.write("\theight : 90px;\r\n");
      out.write("\twidth : 90px;\r\n");
      out.write("\tbackground-color : #DB542D;\r\n");
      out.write("\ttext-align : center;\r\n");
      out.write("\tline-height : 90px;\r\n");
      out.write("\tmargin-top : 2px;\r\n");
      out.write("\tmargin-bottom : 2px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("div.navigation ul li a{\r\n");
      out.write("\tcursor : pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("div.navigation>ul>li>a{\r\n");
      out.write("\tposition : relative;\r\n");
      out.write("\tdisplay : block;\r\n");
      out.write("\tcolor:#FFF;\r\n");
      out.write("\tfont-size : 17px;\r\n");
      out.write("\ttext-decoration : none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("/* ====== Color class ======*/\r\n");
      out.write("div.navigation .color1{\r\n");
      out.write("\tbackground-color : #0097aa;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("div.navigation .color2{\r\n");
      out.write("\tbackground-color : #9f00a7;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("div.navigation .color3{\r\n");
      out.write("\tbackground-color: #63C;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("div.navigation .color4{\r\n");
      out.write("\tbackground-color : #bb1d48;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* ====== title span ====== */\r\n");
      out.write("\r\n");
      out.write("div.navigation span{\r\n");
      out.write("\tposition : relative;\r\n");
      out.write("\tfont-family : 'Open Sans';\r\n");
      out.write("\tfont-weight : 300;\r\n");
      out.write("\tfont-size : 16px;\r\n");
      out.write("\tmargin-left : 40px;\r\n");
      out.write("\tfont-size : 28px;\r\n");
      out.write("\tcolor : white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("#color{ margin-left:40px;}\r\n");
      out.write("#color li{  float:left; margin:0 5px;}\r\n");
      out.write("div.navigation ul li a:hover{ background-color: #CCC; color:#00C;}\r\n");
      out.write("#logo{ width:100%;}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class = \"navigation\">\r\n");
      out.write("\t<div id=\"logo\">\r\n");
      out.write("\t\t<span><img src=\"/phonemarket/image/logo.png\" width=\"350\" height=\"85\"></span> \r\n");
      out.write("\t</div>\r\n");
      out.write("\t<ul id=\"color\"> \r\n");
      out.write("\t\t<li class = \"color1\"><a href = \"/phonemarket/user/index.jsp\">前台主页</a></li>\r\n");
      out.write("\t\t<li><a href = \"/phonemarket/admin/employeelist.jsp\">管理员列表</a></li>\r\n");
      out.write("\t\t<li class = \"color2\"><a href = \"/phonemarket/admin/userStateManage.jsp\">用户列表</a></li>\r\n");
      out.write("\t\t<li class = \"color3\"><a href = \"/phonemarket/admin/companylist.jsp\">公司列表</a></li>\r\n");
      out.write("\t\t<li class = \"color4\"><a href = \"/phonemarket/admin/phonelist.jsp\">手机列表</a></li>\r\n");
      out.write("\t\t<li><a href = \"orderlist.jsp\">订单列表</a></li>\r\n");
      out.write("\t</ul> \r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("</div> \r\n");
      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
